export const questions: string[] = [
  "Hva kalles frykten for dukker?",
  "Hva kalles frykten for mørke?",
  "Hva kalles frykten for blomster?",
  "Hva kalles frykten for vann?",
  "Hva kalles frykten for speil?",
  "Hva kalles frykten for fugler?",
  "Hva kalles frykten for tannleger?",
  "Hva kalles frykten for høye lyder?",
  "Hva kalles frykten for skjegg?",
  "Hva kalles frykten for tall?",
  "Hva kalles studiet av penger?",
  "Hva kalles studiet av vinproduksjon?",
  "Hva kalles studiet av språk?",
  "Hva kalles studiet av bier?",
  "Hva kalles studiet av sopp?",
  "Hva kalles studiet av jordskjelv?",
  "Hva kalles studiet av kart?",
  "Hva kalles studiet av drømmer?",
  "Hva kalles studiet av fisk?",
  "Hva kalles studiet av ords opprinnelse?",
  "Hva betyr ordet 'karaoke' på japansk?",
  "Hva betyr ordet 'robot' opprinnelig på tsjekkisk?",
  "Hva betyr ordet 'tsunami' på japansk?",
  "Hva betyr ordet 'chocolate' opprinnelig?",
  "Hva betyr ordet 'safari' på swahili?",
  "Hva betyr ordet 'whiskey' på gælisk?",
  "Hva betyr ordet 'alphabet' egentlig?",
  "Hva betyr ordet 'penguin' opprinnelig?",
  "Hva betyr ordet 'origami' på japansk?",
  "Hva betyr ordet 'piano' på italiensk?",
  "Hvilket dyr kan ikke stikke avkommet sitt selv om det har gift?",
  "Hvilket dyr kan ikke stikke tungen ut av munnen?",
  "Hvilket dyr kan ikke hoppe?",
  "Hvilket dyr kan ikke svette?",
  "Hvilket dyr kan ikke se opp?",
  "Hvilket dyr kan ikke svelge uten vann?",
  "Hvilket dyr kan ikke gå baklengs?",
  "Hvilket dyr kan ikke hoste?",
  "Hvilket dyr kan ikke lukke øynene?",
  "Hvilket dyr kan ikke bevege øynene sine?",
  "Hva var den første filmen som ble vist med 3D-briller?",
  "Hva var den første TV-serien som ble sendt i farger?",
  "Hva var den første filmen som ble vist på kino?",
  "Hva var den første filmen som vant Oscar?",
  "Hva var den første TV-serien med over 10 sesonger?",
  "Hva var den første videoen lastet opp på YouTube?",
  "Hva var den første radiooverføringen av et sportsarrangement?",
  "Hva var den første sangen som ble spilt på MTV?",
  "Hva var den første datamaskinen som kunne spille musikk?",
  "Hva var den første boka som ble trykt i Europa?",
  "Hva var Super Glue opprinnelig utviklet for?",
  "Hva var bubble wrap opprinnelig laget for?",
  "Hva var Play-Doh opprinnelig laget for?",
  "Hva var Cornflakes opprinnelig laget for å forhindre?",
  "Hva var WD-40 opprinnelig utviklet for?",
  "Hva var Viagra opprinnelig utviklet for?",
  "Hva var Coca-Cola opprinnelig solgt som?",
  "Hva var Nutella opprinnelig laget som erstatning for?",
  "Hva var Kleenex opprinnelig markedsført som?",
  "Hva var Silly Putty opprinnelig utviklet som erstatning for?",
  "Hvilket firma oppfant den første elektriske støvsugeren?",
  "Hvilket firma oppfant den første smartklokken?",
  "Hvilket firma oppfant den første bærbare datamaskinen?",
  "Hvilket firma oppfant Post-it-lapper?",
  "Hvilket firma oppfant kredittkortet?",
  "Hvilket firma oppfant den første dataviruset?",
  "Hvilket firma oppfant e-posten?",
  "Hvilket firma oppfant det første digitale kameraet?",
  "Hvilket firma oppfant den første mobiltelefonen?",
  "Hvilket firma oppfant den første fjernkontrollen?",
  "Hvilket land har verdens eldste nasjonalsang?",
  "Hvilket land drikker mest kaffe per innbygger?",
  "Hvilket land har flest øyer?",
  "Hvilket land har verdens korteste arbeidsuke?",
  "Hvilket land har verdens lengste kystlinje?",
  "Hvilket land har flest offisielle språk?",
  "Hvilket land har flest vulkaner?",
  "Hvilket land har flest naboer?",
  "Hvilket land har flest ørkener?",
  "Hvilket land har flest Nobelprisvinnere?",
  "Hva er den eneste muskelen i kroppen som bare er festet i én ende?",
  "Hva er det eneste beinet i kroppen som ikke er koblet til et annet?",
  "Hva er den minste knokkelen i kroppen?",
  "Hva er den største knokkelen i kroppen?",
  "Hva er den eneste delen av kroppen som ikke får blodtilførsel?",
  "Hva er det eneste organet som kan regenerere seg selv?",
  "Hva er det mest elastiske organet i kroppen?",
  "Hva er det sterkeste muskelen i kroppen i forhold til størrelse?",
  "Hva er det eneste stedet på kroppen som ikke får arr?",
  "Hva er det eneste stedet på kroppen der håret aldri vokser?",
  "Hva var den første drikken som ble solgt i en boks?",
  "Hva var den første drikken som ble kalt en soft drink?",
  "Hva var den første drikken som ble solgt på flaske?",
  "Hva var den første sjokoladen som ble solgt i barform?",
  "Hva var den første maten som ble mikrobølget?",
  "Hva var den første pizzaen som ble solgt med levering?",
  "Hva var den første retten som ble servert på McDonald's?",
  "Hva var den første iskremen som ble solgt kommersielt?",
  "Hva var det første produktet som ble solgt i en salgsautomat?",
  "Hva var den første teen som ble importert til Europa?",
  "Hva var den første frukten som ble spist på månen?",
  "Hva var det første ordet som ble sendt via telefon?",
  "Hva var den første nettsiden som ble laget?",
  "Hva var den første boka som ble skrevet på skrivemaskin?",
  "Hva var den første filmen som brukte CGI?",
  "Hva var det første dyret som ble klonet?",
  "Hva var det første spillet som ble laget for datamaskin?",
  "Hva var den første filmen som spilte inn over 1 milliard dollar?",
  "Hva var den første TV-serien som ble streamet på Netflix?",
  "Hva var det første landet som ga kvinner stemmerett?",
  "Hva betyr ordet 'kindergarten' på tysk?",
  "Hva betyr ordet 'sushi' på japansk?",
  "Hva betyr ordet 'karaoke' på japansk?",
  "Hva betyr ordet 'algebra' på arabisk?",
  "Hva betyr ordet 'safari' på swahili?",
  "Hva betyr ordet 'kangaroo' på aboriginsk språk?",
  "Hva betyr ordet 'tattoo' på polynesisk?",
  "Hva betyr ordet 'vodka' på russisk?",
  "Hva betyr ordet 'emoji' på japansk?",
  "Hva betyr ordet 'yoga' på sanskrit?",
  "Hva kalles frykten for torden?",
  "Hva kalles frykten for å fly?",
  "Hva kalles frykten for hunder?",
  "Hva kalles frykten for trange rom?",
  "Hva kalles frykten for edderkopper?",
  "Hva kalles frykten for høyder?",
  "Hva kalles frykten for å snakke i telefon?",
  "Hva kalles frykten for å bli sett på?",
  "Hva kalles frykten for store folkemengder?",
  "Hva kalles frykten for bakterier?",
  "Hvilket dyr kan sove stående?",
  "Hvilket dyr kan gjenkjenne seg selv i speil?",
  "Hvilket dyr kan se ultrafiolett lys?",
  "Hvilket dyr kan bytte kjønn?",
  "Hvilket dyr kan huske ansikter i flere år?",
  "Hvilket dyr har den lengste tungen i forhold til kroppsstørrelse?",
  "Hvilket dyr har det kraftigste bittet?",
  "Hvilket dyr har flest hjerter?",
  "Hvilket dyr har størst øyne?",
  "Hvilket dyr har blått blod?",
  "Hva var den første byen som fikk trafikklys?",
  "Hva var den første byen som fikk elektriske gatelys?",
  "Hva var den første byen som fikk undergrunnsbane?",
  "Hva var den første byen som fikk telefon?",
  "Hva var den første byen som fikk kloakksystem?",
  "Hva var den første byen som fikk pizza-levering?",
  "Hva var den første byen som fikk Wi-Fi gratis?",
  "Hva var den første byen som fikk asfaltveier?",
  "Hva var den første byen som fikk offentlige toaletter?",
  "Hva var den første byen som fikk sykehus?",
  "Hvilket land oppfant sjakk?",
  "Hvilket land oppfant is?",
  "Hvilket land oppfant pizza?",
  "Hvilket land oppfant kaffe?",
  "Hvilket land oppfant ost?",
  "Hvilket land oppfant pasta?",
  "Hvilket land oppfant papiret?",
  "Hvilket land oppfant trykkpressen?",
  "Hvilket land oppfant tannkrem?",
  "Hvilket land oppfant sykkel?",
  "Hva var bubble wrap først tenkt brukt som?",
  "Hva var Barbie-dukken først laget for?",
  "Hva var M&Ms først laget for?",
  "Hva var cornflakes laget for å forhindre?",
  "Hva var Coca-Cola opprinnelig markedsført som?",
  "Hva var 7Up opprinnelig markedsført som?",
  "Hva var ketchup opprinnelig solgt som medisin for?",
  "Hva var potetgull først oppfunnet som?",
  "Hva var sandwich oppfunnet for?",
  "Hva var Red Bull først laget for?",
  "Hva var den første datamaskinen som kunne lagre programvare?",
  "Hva var den første datamaskinen som brukte mus?",
  "Hva var den første e-posten sendt til?",
  "Hva var den første nettsiden om?",
  "Hva var det første domenet som ble registrert?",
  "Hva var det første bildet lastet opp på internett?",
  "Hva var det første spillet for mobiltelefon?",
  "Hva var den første nettleseren?",
  "Hva var den første videoen lastet opp på YouTube?",
  "Hva var den første søkemotoren?",
  "Hva er det eneste kontinentet uten bjørner?",
  "Hva er det eneste kontinentet uten slangearter?",
  "Hva er det eneste kontinentet uten katter?",
  "Hva er det eneste kontinentet uten bier?",
  "Hva er det eneste kontinentet uten krokodiller?",
  "Hva er det eneste kontinentet uten pingviner?",
  "Hva er det eneste kontinentet uten edderkopper?",
  "Hva er det eneste kontinentet uten aper?",
  "Hva er det eneste kontinentet uten elver?",
  "Hva er det eneste kontinentet uten ørkener?",
  "Hvilket land har verdens dyreste kaffe?",
  "Hvilket land har verdens høyeste bygning?",
  "Hvilket land har flest McDonald's per innbygger?",
  "Hvilket land har flest pizza-restauranter per innbygger?",
  "Hvilket land har flest Nobelprisvinnere per innbygger?",
  "Hvilket land har flest museer?",
  "Hvilket land har flest biblioteker?",
  "Hvilket land har flest språk?",
  "Hvilket land har flest fjelltopper over 8000 meter?",
  "Hvilket land har flest innsjøer?",
];

export const correctAnswers: string[] = [
  "Pediophobia",
  "Nyctophobia",
  "Anthophobia",
  "Aquaphobia",
  "Eisoptrophobia",
  "Ornithophobia",
  "Dentophobia",
  "Phonophobia",
  "Pogonophobia",
  "Arithmophobia",
  "Numismatikk",
  "Oenologi",
  "Lingvistikk",
  "Apiologi",
  "Mykologi",
  "Seismologi",
  "Kartografi",
  "Oneirologi",
  "Iktyologi",
  "Etymologi",
  "Tomt orkester",
  "Tvangsarbeid",
  "Havnebølge",
  "Bitter vann",
  "Reise",
  "Livets vann",
  "Første to bokstaver i det greske alfabetet",
  "Hvit hode",
  "Brette papir",
  "Mykt",
  "Skorpion",
  "Krokodille",
  "Elefant",
  "Gris",
  "Giraff",
  "Skilpadde",
  "Kenguru",
  "Hest",
  "Fisk",
  "Ugle",
  "Bwana Devil",
  "Bonanza",
  "The Jazz Singer",
  "Wings",
  "Gunsmoke",
  "Me at the zoo",
  "Boxing",
  "Video Killed the Radio Star",
  "CSIRAC",
  "Bibelen",
  "Våpenoptikk",
  "Tapet",
  "Tapet-rens",
  "Onani",
  "Rustforebygging",
  "Angina",
  "Medisin mot hodepine",
  "Sjokolade",
  "Sminkefjerner",
  "Gummierstatning",
  "Hoover",
  "Seiko",
  "Osborne",
  "3M",
  "Diners Club",
  "IBM",
  "ARPANET",
  "Kodak",
  "Motorola",
  "Zenith",
  "Japan",
  "Finland",
  "Sverige",
  "Nederland",
  "Canada",
  "Sør-Afrika",
  "Indonesia",
  "Kina",
  "Australia",
  "USA",
  "Tungen",
  "Hyoid-beinet",
  "Stigbøylen",
  "Lårbeinet",
  "Hornhinnen",
  "Leveren",
  "Huden",
  "Kjevemuskelen",
  "Øynene",
  "Håndflaten",
  "Øl",
  "Ginger ale",
  "Mineralvann",
  "Fry’s Chocolate Cream",
  "Popcorn",
  "Lunsjpizza",
  "Hamburger",
  "Vaniljeis",
  "Tyggegummi",
  "Grønn te",
  "Fersken",
  "Hallo",
  "info.cern.ch",
  "Tom Sawyer",
  "Tron",
  "Dolly sau",
  "Spacewar!",
  "Titanic",
  "House of Cards",
  "New Zealand",
  "Barnhage",
  "Surt ris",
  "Tomt orkester",
  "Gjenforening",
  "Reise",
  "Jeg forstår ikke",
  "Å tegne",
  "Liten vann",
  "Bilde-tegn",
  "Forening",
  "Astraphobia",
  "Aviophobia",
  "Cynophobia",
  "Claustrophobia",
  "Arachnophobia",
  "Acrophobia",
  "Telephonophobia",
  "Scopophobia",
  "Agoraphobia",
  "Mysophobia",
  "Hest",
  "Sjimpanse",
  "Bie",
  "Clownfisk",
  "Elefant",
  "Maurtunge",
  "Saltvannskrokodille",
  "Blekksprut",
  "Kjempeblekksprut",
  "Hestesko-krabbe",
  "Cleveland",
  "Paris",
  "London",
  "Boston",
  "Roma",
  "Napoli",
  "Tallinn",
  "London",
  "Paris",
  "Bagdad",
  "India",
  "Kina",
  "Italia",
  "Etiopia",
  "Frankrike",
  "Kina",
  "Tyskland",
  "Egypt",
  "Frankrike",
  "Tyskland",
  "Tapet",
  "Voksenleke",
  "Soldater under krig",
  "Onani",
  "Nervemedisin",
  "Litium",
  "Diaré",
  "Klagerestaurant",
  "Spillkort",
  "Energidrikk",
  "Manchester Baby",
  "Xerox Alto",
  "Seg selv",
  "Prosjektbeskrivelse",
  "symbolics.com",
  "En band",
  "Snake",
  "Mosaic",
  "Me at the zoo",
  "Archie",
  "Antarktis",
  "Antarktis",
  "Antarktis",
  "Antarktis",
  "Europa",
  "Afrika",
  "Antarktis",
  "Antarktis",
  "Antarktis",
  "Antarktis",
  "Etiopia",
  "De forente arabiske emirater",
  "USA",
  "Italia",
  "Sveits",
  "USA",
  "USA",
  "India",
  "Nepal",
  "Canada",
];

export const playerEmojis: string[] = [
  "🐸",
  "🦊",
  "🐻",
  "🐼",
  "🐨",
  "🦁",
  "🐯",
  "🐮",
  "🐷",
  "🐵",
  "🐶",
  "🐱",
  "🐭",
  "🐹",
  "🐰",
  "🦝",
  "🐺",
  "🐧",
  "🦅",
  "🦉",
  "🐙",
  "🦞",
  "🐢",
  "🦎",
  "🐍",
  "🐲",
  "🦄",
  "🐝",
  "🦋",
  "🌟",
  "⭐",
  "💫",
  "🔥",
  "❄️",
  "⚡",
  "🌈",
  "🍀",
  "🌺",
  "🌸",
];

export const DEFAULT_MAX_GUESSES = 3;
export const MIN_PLAYERS = 2;
